"""
Seller / Inventory Screen  [F3]
================================
Flow A — Seller (Automatic Waste Generation):
  1. Company registers its primary product
  2. "Run AI Scan" → Gemini predicts probable industrial byproducts
  3. Each predicted byproduct is filtered through the Hazard Checker
  4. Non-hazardous items are auto-listed as pending → approved in inventory
  5. Hazardous items are quarantined (status=blocked) with reason shown

The screen also lets users:
  - Manually add custom product/byproduct listings
  - View all their listings with status pills
  - Delete their own listings
"""

from __future__ import annotations

import asyncio
from typing import Any

from textual import on, work
from textual.app import ComposeResult
from textual.containers import Container, Horizontal, Vertical
from textual.widgets import Button, DataTable, Label, LoadingIndicator, RichLog, Static

from circularlink.core.gemini_agent import GeminiAgent
from circularlink.core.hazard import HazardChecker
from circularlink.core.geo import GeoService
from circularlink.storage.db import Database


class SellerScreen(Container):
    """F3 — Sell: Inventory (AI-Generated Byproducts)."""

    DEFAULT_CSS = """
    SellerScreen { background: #1A1B26; overflow-y: auto; }
    .section-title {
        background: #24253A;
        color: #E06C75;
        text-style: bold;
        height: 3;
        padding: 0 2;
        content-align: left middle;
        border-bottom: solid #E06C75;
        margin-bottom: 1;
    }
    .ai-banner {
        background: #1A2535;
        color: #61AFEF;
        border: solid #61AFEF;
        height: 3;
        padding: 0 2;
        content-align: left middle;
        margin: 0 2 1 2;
    }
    DataTable {
        background: #1A1B26;
        border: solid #3E4451;
        margin: 0 2 1 2;
        height: 12;
    }
    DataTable > .datatable--header {
        background: #24253A;
        color: #E06C75;
        text-style: bold;
    }
    DataTable > .datatable--cursor { background: #2E3052; }
    RichLog {
        background: #1A1B26;
        border: solid #3E4451;
        margin: 0 2 1 2;
        height: 10;
    }
    #btn-row { height: 3; margin: 0 2 1 2; }
    Button { margin-right: 1; }
    LoadingIndicator { color: #61AFEF; height: 3; }
    """

    def __init__(self, company_id: str) -> None:
        super().__init__()
        self._company_id = company_id
        self._hazard_checker = HazardChecker()

    def compose(self) -> ComposeResult:
        yield Static("  Sell: Inventory  (AI-Generated Byproducts)", classes="section-title")
        yield Static(
            "  Gemini analyses your primary product to predict probable industrial byproducts. "
            "All listings are auto-screened against the Hazardous Substances register.",
            classes="ai-banner",
        )
        with Horizontal(id="btn-row"):
            yield Button("  Run AI Byproduct Scan", id="btn-ai-scan", classes="btn-ai")
            yield Button("  Add Manually", id="btn-add-manual", classes="btn-sell")
            yield Button("  Refresh List", id="btn-refresh", variant="default")
            yield Button("  Delete Selected", id="btn-delete", classes="btn-danger")
        yield LoadingIndicator(id="loading", classes="loading")
        yield Static("  Your Listings", classes="section-title")
        yield DataTable(id="inventory-table", zebra_stripes=True, cursor_type="row")
        yield Static("  AI / Hazard Processing Log", classes="section-title")
        yield RichLog(id="sell-log", highlight=True, markup=True)

    def on_mount(self) -> None:
        indicator = self.query_one("#loading", LoadingIndicator)
        indicator.display = False
        self._build_table()
        self._load_listings()

    def _build_table(self) -> None:
        table = self.query_one("#inventory-table", DataTable)
        table.add_columns("Product Name", "Description", "Qty", "Unit", "City", "Status", "Created")

    def _load_listings(self) -> None:
        table = self.query_one("#inventory-table", DataTable)
        table.clear()
        products = Database.products_by_company(self._company_id)
        products.sort(key=lambda p: p.get("created_at", ""), reverse=True)
        for p in products:
            status = p.get("status", "pending")
            status_styled = {
                "approved": "[green]✓ approved[/green]",
                "blocked":  "[red]✗ blocked[/red]",
                "pending":  "[yellow]⏳ pending[/yellow]",
            }.get(status, status)
            desc = (p.get("description", "") or "")[:50]
            created = str(p.get("created_at", ""))[:10]
            table.add_row(
                p.get("name", ""),
                desc,
                str(p.get("quantity", "")),
                p.get("unit", ""),
                p.get("city", ""),
                status_styled,
                created,
                key=p.get("product_id", ""),
            )

    def _log(self, msg: str) -> None:
        try:
            self.query_one("#sell-log", RichLog).write(msg)
        except Exception:
            pass

    # ── AI Byproduct Scan ───────────────────────────────────────────────────

    @on(Button.Pressed, "#btn-ai-scan")
    def _trigger_ai_scan(self) -> None:
        self._run_ai_scan()

    @work(thread=True)
    def _run_ai_scan(self) -> None:
        """Background worker: Gemini → Hazard check → DB upsert."""
        self.app.call_from_thread(self._set_loading, True)
        self.app.call_from_thread(self._log, "[cyan]  Gemini: Starting byproduct analysis…[/cyan]")

        company = Database.get_company(self._company_id)
        if not company:
            self.app.call_from_thread(self._log, "[red]✗ Company record not found.[/red]")
            self.app.call_from_thread(self._set_loading, False)
            return

        product_desc = company.get("primary_product", "")
        if not product_desc:
            self.app.call_from_thread(
                self._log,
                "[yellow]⚠ No primary product registered. Update in KYC/Settings first.[/yellow]",
            )
            self.app.call_from_thread(self._set_loading, False)
            return

        api_key = Database.get_api_key()
        if not api_key:
            self.app.call_from_thread(
                self._log,
                "[red]✗ No Gemini API key configured. Set it in KYC/Settings.[/red]",
            )
            self.app.call_from_thread(self._set_loading, False)
            return

        try:
            agent = GeminiAgent(api_key=api_key)
        except Exception as exc:
            self.app.call_from_thread(self._log, f"[red]✗ Gemini init failed: {exc}[/red]")
            self.app.call_from_thread(self._set_loading, False)
            return

        self.app.call_from_thread(
            self._log,
            f"[cyan]  Gemini: Analysing '{product_desc[:60]}…'[/cyan]",
        )

        response = agent.predict_byproducts(
            product_description=product_desc,
            product_id=self._company_id,
        )

        if not response.success:
            self.app.call_from_thread(
                self._log,
                f"[red]✗ Gemini error: {response.error}[/red]",
            )
            self.app.call_from_thread(self._set_loading, False)
            return

        self.app.call_from_thread(
            self._log,
            f"[cyan]  Gemini: Found {len(response.predicted_materials)} predicted byproducts "
            f"(latency {response.latency_ms:.0f}ms)[/cyan]",
        )

        # Resolve company city / coords
        company_city = company.get("city", "")
        lat = float(company.get("latitude", 0) or 0)
        lon = float(company.get("longitude", 0) or 0)
        if lat == 0 or lon == 0:
            coords = GeoService.lookup_city(company_city)
            if coords:
                lat, lon = coords.lat, coords.lon
                Database.upsert_company({**company, "latitude": lat, "longitude": lon})

        new_listed = 0
        blocked = 0

        for mat in response.predicted_materials:
            hazard = self._hazard_checker.check(mat.material, mat.description)
            if hazard.is_hazardous:
                self.app.call_from_thread(
                    self._log,
                    f"[red]  BLOCKED [{hazard.hazard_class}]: {mat.material} "
                    f"— {hazard.matched_name} (via {hazard.match_type})[/red]",
                )
                # Still record it as blocked for audit
                Database.upsert_product(
                    {
                        "company_id": self._company_id,
                        "company_name": company.get("name", ""),
                        "name": mat.material,
                        "description": mat.description,
                        "quantity": 0,
                        "unit": "",
                        "city": company_city,
                        "lat": lat,
                        "lon": lon,
                        "status": "blocked",
                        "hazard_class": hazard.hazard_class,
                    }
                )
                blocked += 1
            else:
                self.app.call_from_thread(
                    self._log,
                    f"[green]  LISTED: {mat.material}[/green] — {mat.description[:60]}",
                )
                Database.upsert_product(
                    {
                        "company_id": self._company_id,
                        "company_name": company.get("name", ""),
                        "name": mat.material,
                        "description": mat.description,
                        "quantity": 0,
                        "unit": "",
                        "city": company_city,
                        "lat": lat,
                        "lon": lon,
                        "status": "approved",
                        "hazard_class": None,
                    }
                )
                new_listed += 1

        self.app.call_from_thread(
            self._log,
            f"[bold]  Summary: {new_listed} listed ✓ | {blocked} blocked ✗[/bold]",
        )
        self.app.call_from_thread(self._set_loading, False)
        self.app.call_from_thread(self._load_listings)
        self.app.call_from_thread(
            self.app.notify,
            f"AI scan complete: {new_listed} listed, {blocked} blocked",
            severity="information",
        )

    # ── Manual add ──────────────────────────────────────────────────────────

    @on(Button.Pressed, "#btn-add-manual")
    def _add_manual(self) -> None:
        from circularlink.screens.modals import AddProductModal

        def _on_result(result: dict | None) -> None:
            if not result:
                return
            company = Database.get_company(self._company_id)
            if not company:
                return
            city = result.get("city_override") or company.get("city", "")
            lat  = float(company.get("latitude", 0) or 0)
            lon  = float(company.get("longitude", 0) or 0)
            if city and (lat == 0 or lon == 0):
                coords = GeoService.lookup_city(city)
                if coords:
                    lat, lon = coords.lat, coords.lon

            hazard = self._hazard_checker.check(
                result["name"], result.get("description", "")
            )
            status = "blocked" if hazard.is_hazardous else "approved"
            hclass = hazard.hazard_class if hazard.is_hazardous else None

            product = Database.upsert_product(
                {
                    "company_id": self._company_id,
                    "company_name": company.get("name", ""),
                    "name": result["name"],
                    "description": result.get("description", ""),
                    "quantity": result.get("quantity", 0),
                    "unit": result.get("unit", ""),
                    "city": city,
                    "lat": lat,
                    "lon": lon,
                    "status": status,
                    "hazard_class": hclass,
                }
            )
            if hazard.is_hazardous:
                self._log(
                    f"[red]✗ BLOCKED [{hazard.hazard_class}]: {result['name']}[/red]"
                )
                self.app.notify(
                    f"'{result['name']}' blocked — hazardous material: {hazard.hazard_class}",
                    severity="warning",
                )
            else:
                self._log(f"[green]✓ Listed: {result['name']}[/green]")
                self.app.notify(f"'{result['name']}' listed successfully", severity="information")
            self._load_listings()

        self.app.push_screen(AddProductModal(), _on_result)

    # ── Refresh / Delete ────────────────────────────────────────────────────

    @on(Button.Pressed, "#btn-refresh")
    def _handle_refresh(self) -> None:
        self._load_listings()

    @on(Button.Pressed, "#btn-delete")
    def _handle_delete(self) -> None:
        table = self.query_one("#inventory-table", DataTable)
        if table.cursor_row < 0:
            self.app.notify("Select a row first", severity="warning")
            return
        row_key = table.get_row_at(table.cursor_row)
        # row_key is the product_id we set via key= in add_row
        # row contains row_key as last element if no explicit column key
        # We used `key=` param so we can retrieve it
        try:
            prod_id = table.get_row_at(table.cursor_row)
            # table.get_row_at returns values; use key from cursor
            row_key_obj = table.coordinate_to_cell_key(table.cursor_coordinate)
            pid = str(row_key_obj.row_key.value)
        except Exception:
            self.app.notify("Could not determine selected product", severity="error")
            return

        from circularlink.screens.modals import ConfirmModal

        def _confirmed(yes: bool) -> None:
            if yes:
                Database.delete_product(pid)
                self._load_listings()
                self._log(f"[dim]Deleted product {pid[:8]}[/dim]")
                self.app.notify("Product deleted", severity="information")

        self.app.push_screen(ConfirmModal("Delete Product", "Are you sure you want to delete this listing?"), _confirmed)

    def _set_loading(self, visible: bool) -> None:
        try:
            self.query_one("#loading", LoadingIndicator).display = visible
        except Exception:
            pass
